### PR TITLE
Update dependencies

### LINKED ISSUE #8: Minimist requires upgrade due to vulnerability
https://snyk.io/test/npm/minimist/0.2.0

### PR DESCRIPTION
**Pull request by hoobdeebla**
Updates all dependencies to latest. Removes highlight.js unsupported notice on first install. Fixes #8 ([minimist vulnerability](https://snyk.io/vuln/SNYK-JS-MINIMIST-559764)). Maintains compatibility with older Node versions but requires Node >=10.12 to run Mocha in development.

### CODE REVIEW

**Comment by hoobdeebla** [comment]
Thoughts @rstacruz?

**Comment by rstacruz** [comment]
Hey this looks great! Let me have a look when I get the time.

**Review by kailan — APPROVED** [review]
It would be great to get this merged as there is a GitHub security alert on Gatsby projects that it resolves.

**Comment by rstacruz** [comment]
Thanks! I've updated the package with a new version. Thanks everyone for all the help.

[Release v0.8.0 - Updated dependencies · rstacruz/hicat](https://github.com/rstacruz/hicat/releases/tag/v0.8.0)

**Pull request merged**
